version: '3.4'

services:
  testefrexco:
    image: testefrexco
    build:
      context: teste-frexco
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7878:7878
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
