version: '3.4'

services:
  testefrexco:
    image: testefrexco
    build:
      context: teste-frexco
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7878:7878
